project_id = "khdiwrkgahsbjszlwnob"

[auth]
enabled = true
# The base URL of your website. Used as an allow-list for redirects and for constructing URLs used
# in emails.
site_url = "http://localhost:3000"
# A list of *exact* URLs that auth providers are permitted to redirect to post authentication.
additional_redirect_urls = ["https://localhost:3000"]
# How long tokens are valid for, in seconds. Defaults to 3600 (1 hour), maximum 604800 (1 week).
jwt_expiry = 3600
# Allow/disallow new user signups to your project.
enable_signup = true

[auth.email]
# Allow/disallow new user signups via email to your project.
enable_signup = true
# If enabled, a user will be required to confirm any email change on both the old, and new email addresses.
# If disabled, only the new email is required to confirm.
double_confirm_change = true
# If enabled, users need to confirm their email address before signing in.
enable_confirmations = false

# Use pre-defined map of claims
[auth.jwt]
[auth.jwt.template]

[[auth.jwt.template.claims]]
name = "email"
value = "email"

[[auth.jwt.template.claims]]
name = "phone"
value = "phone"

[[auth.jwt.template.claims]]
name = "app_metadata"
value = "app_metadata"

[[auth.jwt.template.claims]]
name = "user_metadata"
value = "user_metadata"

[functions.send-cue-trigger]
verify_jwt = false

[functions.rundown-api]
verify_jwt = false

[functions.cleanup-test-account]
verify_jwt = false

[functions.send-welcome-email]
verify_jwt = false