
import { RundownItem } from './rundown';
import { Column } from '@/hooks/useColumnsManager';
import React from 'react';

export interface RundownContainerProps {
  currentTime: Date;
  timezone: string;
  onTimezoneChange: (timezone: string) => void;
  totalRuntime: string;
  showColumnManager: boolean;
  setShowColumnManager: (show: boolean) => void;
  items: RundownItem[];
  visibleColumns: Column[];
  columns: Column[];
  showColorPicker: boolean;
  cellRefs: React.MutableRefObject<{ [key: string]: HTMLElement | null }>;
  selectedRows: Set<string>;
  draggedItemIndex: number | null;
  isDraggingMultiple: boolean;
  dropTargetIndex: number | null;
  currentSegmentId: string | null;
  getColumnWidth: (columnId: string) => number;
  updateColumnWidth: (columnId: string, width: number) => void;
  getRowNumber: (index: number) => string;
  getRowStatus: (item: RundownItem) => 'past' | 'current' | 'upcoming';
  calculateHeaderDuration: (headerIndex: number) => string;
  onUpdateItem: (id: string, field: string, value: any) => void;
  onCellClick: (itemId: string, columnId: string, event: React.MouseEvent) => void;
  onKeyDown: (event: React.KeyboardEvent) => void;
  onToggleColorPicker: (itemId?: string) => void;
  onColorSelect: (id: string, color: string) => void;
  onDeleteRow: (id: string) => void;
  onToggleFloat: (id: string) => void;
  onRowSelect: (itemId: string, event: React.MouseEvent) => void;
  onDragStart: (index: number) => void;
  onDragOver: (index: number) => void;
  onDragLeave: () => void;
  onDrop: (targetIndex: number) => void;
  onAddRow: () => void;
  onAddHeader: () => void;
  selectedCount: number;
  hasClipboardData: boolean;
  onCopySelectedRows: () => void;
  onPasteRows: () => void;
  onDeleteSelectedRows: () => void;
  onClearSelection: () => void;
  selectedRowId: string | null;
  isPlaying: boolean;
  timeRemaining: string;
  onPlay: () => void;
  onPause: () => void;
  onForward: () => void;
  onBackward: () => void;
  handleAddColumn: (name: string, type: string) => void;
  handleReorderColumns: (startIndex: number, endIndex: number) => void;
  handleDeleteColumnWithCleanup: (id: string) => void;
  handleRenameColumn: (id: string, newName: string) => void;
  handleToggleColumnVisibility: (id: string) => void;
  handleLoadLayout: (columns: Column[]) => void;
  hasUnsavedChanges: boolean;
  isSaving: boolean;
  rundownTitle: string;
  onTitleChange: (title: string) => void;
  rundownStartTime: string;
  onRundownStartTimeChange: (time: string) => void;
  rundownId: string;
  onOpenTeleprompter: () => void;
  onUndo: () => void;
  canUndo: boolean;
  lastAction: string;
  // New polling props
  hasRemoteUpdates?: boolean;
  clearRemoteUpdatesIndicator?: () => void;
}
