
// This file is automatically generated. Do not edit it directly.
import { supabase } from '@/lib/supabase';
import type { Database } from './types';

// Re-export the supabase client to ensure consistency
export { supabase };
export type { Database };
